# -*- coding: utf-8 -*-
"""consume_stats.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wLzssIiWS3Lhr0n0tELMzI9EipdrFi6L
"""

from kafka import KafkaConsumer
import json
import datetime

# Initialize Kafka consumer
consumer = KafkaConsumer(
    'zonal-stats',
    bootstrap_servers=['localhost:9092'],
    auto_offset_reset='earliest',
    value_deserializer=lambda x: json.loads(x.decode('utf-8'))
)

# Open a file to store the results
with open('zonal_stats_results.txt', 'w') as f:
    # Process each message
    for message in consumer:
        # Get the value
        data = message.value

        # Format timestamp
        timestamp = datetime.datetime.fromtimestamp(
            message.timestamp / 1000.0
        ).strftime('%Y-%m-%d %H:%M:%S')

        # Write to file
        result_line = f"Time: {timestamp}, " \
                     f"Region: {data['region_id']}, " \
                     f"Stat: {data['stat_value']}\n"
        f.write(result_line)

        # Also print to console
        print(result_line, end='')