# -*- coding: utf-8 -*-
"""produce_tiles.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wLzssIiWS3Lhr0n0tELMzI9EipdrFi6L
"""

from kafka import KafkaProducer
import rasterio
import pickle
from io import BytesIO
import time
import os

# Import functions from your existing raster code
from raster_methods import *  # Adjust import as needed

# Function to serialize tile data
def serialize(tile_data):
    buffer = BytesIO()
    pickle.dump(tile_data, buffer)
    return buffer.getvalue()

# Initialize Kafka producer
producer = KafkaProducer(
    bootstrap_servers='localhost:9092',
    value_serializer=lambda v: serialize(v)
)

# Directory containing your TIFF files

tiff_directory = "/Users/devagopalam/desktop/raptor-cs6964-main/dataset"  # Update this path

# Function to split a raster into tiles
def generate_tiles(raster_path, tile_size=256):
    # This function could use methods from your raster_methods.py
    # or implement a new tiling approach

    with rasterio.open(raster_path) as src:
        meta = src.meta.copy()
        height = src.height
        width = src.width

        # Generate tiles
        for y in range(0, height, tile_size):
            for x in range(0, width, tile_size):
                window = rasterio.windows.Window(x, y,
                                              min(tile_size, width - x),
                                              min(tile_size, height - y))

                # Read the data in the window
                data = src.read(window=window)

                # Create tile metadata
                tile_meta = meta.copy()
                tile_meta.update({
                    'height': window.height,
                    'width': window.width,
                    'transform': rasterio.windows.transform(window, src.transform)
                })

                yield {
                    'data': data,
                    'meta': tile_meta,
                    'window': {
                        'x': x,
                        'y': y,
                        'width': window.width,
                        'height': window.height
                    },
                    'filename': os.path.basename(raster_path)
                }

# Process each TIFF file in the directory
for filename in os.listdir(tiff_directory):
    if filename.endswith(".tif") or filename.endswith(".tiff"):
        file_path = os.path.join(tiff_directory, filename)
        print(f"Processing {file_path}")

        # Generate tiles for the current file
        for tile in generate_tiles(file_path):
            # Send tile to Kafka
            producer.send("raw-tiles", value=tile)

            # Small delay to avoid overwhelming the system
            time.sleep(0.1)

        # Ensure all messages are sent
        producer.flush()

print("All tiles have been sent to Kafka")